//! Bakes the Rust core's tables into C headers for the 6502 build.
//!
//! This is the bridge between the two halves of the project, and the reason
//! the Plus/4 build does not have its own copy of anything.  The character
//! set, the sine table, the reciprocals and the city are all *generated by
//! the same code the terminal renderer uses*, so there is exactly one
//! definition of what a dither glyph looks like, one city generator, and one
//! answer to what colour a building is.
//!
//! The 6502 gets those answers as data.  It does not recompute them - it
//! could not afford to - and it cannot disagree with them, because it has
//! nothing to disagree with.
//!
//! Everything written here is generated, so nothing written here is
//! committed; `make bake` runs before every target build.
//!
//! ```text
//! ascitty-bake --out targets/plus4/gen
//!   charset.h   1024 bytes  the 128 glyphs, 8 bytes each, TED bit order
//!   trig.h       512 bytes  256-entry sine table in Q8.8
//!   recip.h      512 bytes  1/n in Q8.8, for the perspective divide
//!   city.h        ~3 KB     a 48x48 district: heights, colours, tiles
//!   glyphs.h        --      the catalogue's names as #defines
//! ```

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use ascitty_core::catalog::{self, GlyphId};
use ascitty_core::font::{self, Bitmap};
use ascitty_core::glyph::{Mode, ASCII, UNICODE};
use ascitty_core::palette;
use ascitty_core::trig;
use ascitty_core::world::{Arch, City, Kind, SIZE};

/// Side of the district baked for the Plus/4, in cells.
///
/// **64, and it must be a power of two.**  The 6502 has no multiply, so a
/// grid lookup written as `y * SIZE + x` becomes a call to cc65's software
/// multiply - about a hundred cycles - and the DDA does one of those on
/// every step of every column of every frame.  At 48 wide the target build
/// ran at about one frame a second, and that multiply was most of it.  At 64
/// the index is `(y << 6) | x`, which is free.
///
/// The cost is size: 64x64 at three bytes a cell is 12 KB against 6.75 KB,
/// which the machine can afford.  The whole 128x128 city would be 48 KB and
/// could not.  The district is taken from the middle of the map, where the
/// tall buildings are.
const DISTRICT: usize = 64;

/// Bits per fractional part in the Plus/4's fixed point.
const Q: i32 = 8;

struct Opts {
    out: PathBuf,
    seed: u32,
    sheet: bool,
}

const USAGE: &str = "\
ascitty-bake - generate the 6502 build's tables from the Rust core

USAGE: ascitty-bake [options]

  --out DIR     where to write the headers (default: targets/plus4/gen)
  --seed N      city seed; must match the one the host renders
  --sheet       print the glyph catalogue as a character sheet and exit
  -h, --help    this
";

fn main() {
    let mut o = Opts {
        out: PathBuf::from("targets/plus4/gen"),
        seed: ascitty_core::DEFAULT_SEED,
        sheet: false,
    };
    let mut args = std::env::args().skip(1);
    while let Some(a) = args.next() {
        match a.as_str() {
            "-h" | "--help" => {
                print!("{USAGE}");
                return;
            }
            "--out" => o.out = PathBuf::from(args.next().expect("--out needs a directory")),
            "--seed" => o.seed = args.next().expect("--seed needs a number").parse().expect("bad seed"),
            "--sheet" => o.sheet = true,
            _ => {
                eprintln!("ascitty-bake: unknown option {a}\n\n{USAGE}");
                std::process::exit(2);
            }
        }
    }

    if o.sheet {
        print!("{}", sheet());
        return;
    }

    std::fs::create_dir_all(&o.out).expect("cannot create the output directory");
    write(&o.out, "charset.h", &charset());
    write(&o.out, "trig.h", &trig_table());
    write(&o.out, "recip.h", &recip_table());
    write(&o.out, "glyphs.h", &glyph_defines());
    write(&o.out, "city.h", &city(o.seed));
    eprintln!("baked into {}", o.out.display());
}

fn write(dir: &Path, name: &str, body: &str) {
    let path = dir.join(name);
    std::fs::write(&path, body).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    eprintln!("  {} {} bytes", path.display(), body.len());
}

/// The banner every generated header carries.
fn banner(what: &str) -> String {
    format!(
        "/* {what}\n\
         **\n\
         ** GENERATED by ascitty-bake from the ascitty-core crate.\n\
         ** Do not edit: `make bake` overwrites this file, and the generator\n\
         ** is the definition of what these numbers are.\n\
         */\n\n"
    )
}

/// The 128 glyphs, as the TED wants them: one byte per row, bit 7 leftmost.
fn charset() -> String {
    let cat = catalog::build();
    let mut s = banner("charset.h - the procedural block font, 128 glyphs of 8 bytes");
    s.push_str("#ifndef ASCITTY_CHARSET_H\n#define ASCITTY_CHARSET_H\n\n");
    let _ = writeln!(s, "#define CHARSET_GLYPHS {}", catalog::N_GLYPHS);
    let _ = writeln!(s, "#define CHARSET_BYTES  {}\n", catalog::N_GLYPHS * 8);
    s.push_str("extern const unsigned char charset[CHARSET_BYTES];\n\n");
    s.push_str("#ifdef ASCITTY_CHARSET_DATA\nconst unsigned char charset[CHARSET_BYTES] = {\n");
    for (i, bm) in cat.bitmaps.iter().enumerate() {
        let _ = write!(s, "    ");
        for b in bm {
            let _ = write!(s, "0x{b:02x},");
        }
        let _ = writeln!(s, " /* {i:3} {} */", cat.names[i]);
    }
    s.push_str("};\n#endif\n\n#endif\n");
    s
}

/// Sine in Q8.8, 256 entries - a quarter of the host's resolution, which at
/// 40 columns is a third of a character.
fn trig_table() -> String {
    let mut s = banner("trig.h - sine over one turn, Q8.8, 256 entries");
    s.push_str("#ifndef ASCITTY_TRIG_H\n#define ASCITTY_TRIG_H\n\n");
    s.push_str("#define TRIG_LEN  256\n#define TRIG_ONE  256\n");
    s.push_str("#define SIN(a)  (sintab[(unsigned char)(a)])\n");
    s.push_str("#define COS(a)  (sintab[(unsigned char)((a) + 64)])\n\n");
    s.push_str("extern const int sintab[TRIG_LEN];\n\n");
    s.push_str("#ifdef ASCITTY_TRIG_DATA\nconst int sintab[TRIG_LEN] = {\n");
    for row in 0..32 {
        let _ = write!(s, "    ");
        for col in 0..8 {
            let i = row * 8 + col;
            let a = (i as u32 * 65536 / 256) as u16;
            // Q16.16 down to Q8.8, rounding rather than truncating: the
            // truncated table is biased towards zero and a biased sine puts
            // a slow drift into every heading.
            let v = (ascitty_core::trig::sin(a) + 128) >> 8;
            let _ = write!(s, "{v:5},");
        }
        s.push('\n');
    }
    s.push_str("};\n#endif\n\n#endif\n");
    let _ = trig::TRIG_LEN;
    s
}

/// `1/n` in Q8.8 for `n` in `1..=255`.
///
/// The perspective divide is the only division the inner loop needs, and a
/// 6502 has no divide instruction at all - a 16-bit software divide is
/// upwards of 400 cycles.  A 512-byte table replaces every one of them with
/// a multiply, which the machine also lacks but which is four times cheaper
/// to synthesise.
fn recip_table() -> String {
    let mut s = banner("recip.h - 65536/n in Q8.8, for the DDA's step distances");
    s.push_str("#ifndef ASCITTY_RECIP_H\n#define ASCITTY_RECIP_H\n\n");
    // 512 entries, not 256.  The table is indexed by the magnitude of a ray
    // direction component in Q8.8, which reaches 1.0 for the direction plus
    // 0.67 for the plane - about 427 - so a 256-entry table would run off
    // the end for every ray in the outer third of the screen.
    s.push_str("#define RECIP_LEN 512\n\n");
    s.push_str("extern const unsigned int reciptab[RECIP_LEN];\n\n");
    s.push_str("#ifdef ASCITTY_RECIP_DATA\nconst unsigned int reciptab[RECIP_LEN] = {\n");
    for row in 0..64 {
        let _ = write!(s, "    ");
        for col in 0..8 {
            let n = row * 8 + col;
            // Entry 0 is "infinitely near", clamped to the largest value the
            // callers can multiply by without overflowing 16 bits.
            let v: u32 = if n == 0 { 0xffff } else { ((1u32 << (2 * Q)) / n as u32).min(0xffff) };
            // cc65 promotes an unsuffixed constant above INT_MAX to long,
            // and then warns about every entry of the table.  The suffix is
            // not decoration.
            let _ = write!(s, "{v:5}U,");
        }
        s.push('\n');
    }
    s.push_str("};\n#endif\n\n#endif\n");
    s
}

/// The catalogue's names, so the C reads like the Rust.
fn glyph_defines() -> String {
    let mut s = banner("glyphs.h - catalogue indices, which are also screen codes");
    s.push_str("#ifndef ASCITTY_GLYPHS_H\n#define ASCITTY_GLYPHS_H\n\n");
    let defs: [(&str, GlyphId); 22] = [
        ("G_BLANK", catalog::G_BLANK),
        ("G_DITHER", catalog::G_DITHER),
        ("G_SOLID", catalog::G_SOLID),
        ("G_QUAD", catalog::G_QUAD),
        ("G_FILL", catalog::G_FILL),
        ("G_SLOPE", catalog::G_SLOPE),
        ("G_FACADE", catalog::G_FACADE),
        ("G_MULLION", catalog::G_MULLION),
        ("G_CORNICE", catalog::G_CORNICE),
        ("G_FIRE", catalog::G_FIRE),
        ("G_ROOF", catalog::G_ROOF),
        ("G_ROAD", catalog::G_ROAD),
        ("ROAD_ASPHALT", catalog::ROAD_ASPHALT),
        ("ROAD_DASH", catalog::ROAD_DASH),
        ("ROAD_CENTRE", catalog::ROAD_CENTRE),
        ("ROAD_KERB", catalog::ROAD_KERB),
        ("ROAD_PAVING", catalog::ROAD_PAVING),
        ("G_FLORA", catalog::G_FLORA),
        ("G_STREET", catalog::G_STREET),
        ("G_RAIN", catalog::G_RAIN),
        ("G_STAR", catalog::G_STAR),
        ("G_HAZE", catalog::G_HAZE),
    ];
    for (name, v) in defs {
        let _ = writeln!(s, "#define {name:<14} {v}");
    }
    s.push_str("\n/* A TED colour byte: luminance in the high nibble, hue in the low. */\n");
    s.push_str("#define CBYTE(lum, hue) ((unsigned char)(((lum) << 4) | (hue)))\n\n");
    s.push_str("/* Hues, in TED order. */\n");
    for (name, v) in [
        ("HUE_BLACK", palette::H_BLACK),
        ("HUE_WHITE", palette::H_WHITE),
        ("HUE_RED", palette::H_RED),
        ("HUE_CYAN", palette::H_CYAN),
        ("HUE_GREEN", palette::H_GREEN),
        ("HUE_BLUE", palette::H_BLUE),
        ("HUE_YELLOW", palette::H_YELLOW),
        ("HUE_ORANGE", palette::H_ORANGE),
    ] {
        let _ = writeln!(s, "#define {name:<12} {v}");
    }
    s.push_str("\n#endif\n");
    s
}

/// A district of the city, as three parallel byte arrays.
///
/// Structure-of-arrays rather than array-of-structs, because the 6502
/// indexes a byte array with one instruction and a struct array with a
/// multiply it does not have.
fn city(seed: u32) -> String {
    let c = City::generate(seed);
    let off = (SIZE - DISTRICT) / 2;
    let mut s = banner("city.h - a district of the generated city, as a height field");
    s.push_str("#ifndef ASCITTY_CITY_H\n#define ASCITTY_CITY_H\n\n");
    let _ = writeln!(s, "#define CITY_SIZE {DISTRICT}");
    let _ = writeln!(s, "#define CITY_SHIFT {}", DISTRICT.trailing_zeros());
    let _ = writeln!(s, "#define CITY_MASK  {}", DISTRICT - 1);
    s.push_str("/* CITY_SIZE is a power of two so that a grid index is a shift.\n");
    s.push_str("** See the note in ascitty-bake; it is worth a factor of three. */\n");
    let _ = writeln!(s, "#define CITY_SEED {seed}U");
    let _ = writeln!(s, "#define CITY_ORIGIN {off}\n");
    s.push_str("/* Height in world units, 0 for anything you can drive on. */\n");
    s.push_str("extern const unsigned char city_h[CITY_SIZE * CITY_SIZE];\n");
    s.push_str("/* TED colour byte of the facade, at full luminance. */\n");
    s.push_str("extern const unsigned char city_c[CITY_SIZE * CITY_SIZE];\n");
    s.push_str("/* Catalogue index of the facade tile this lot is drawn in. */\n");
    s.push_str("extern const unsigned char city_t[CITY_SIZE * CITY_SIZE];\n\n");

    let mut heights = Vec::with_capacity(DISTRICT * DISTRICT);
    let mut colors = Vec::with_capacity(DISTRICT * DISTRICT);
    let mut tiles = Vec::with_capacity(DISTRICT * DISTRICT);
    for y in 0..DISTRICT {
        for x in 0..DISTRICT {
            let (gx, gy) = ((x + off) as i32, (y + off) as i32);
            let cell = c.at(gx, gy);
            heights.push(cell.height);
            match c.lot_at(gx, gy) {
                Some(lot) => {
                    // The building's own brightness, not a constant: the
                    // Plus/4 gets the same variety the host does.
                    colors.push(palette::rgb_index(lot.hue, lot.luma));
                    // The tile the whole building is drawn in - the same
                    // per-lot choice the host makes, resolved once here so
                    // the 6502 never has to hash anything.
                    let style = (lot.seed >> 17) as u8 & 3;
                    let cfg = match lot.arch {
                        Arch::CurtainWall | Arch::Setback => 0,
                        Arch::Slab | Arch::Deco => 1,
                        Arch::Prewar => 2,
                        Arch::LowRise => 3,
                    };
                    tiles.push(catalog::facade_tile(cfg, style));
                }
                None => {
                    let (col, tile) = match cell.kind {
                        Kind::Road => (palette::rgb_index(palette::H_WHITE, 1), catalog::ROAD_ASPHALT),
                        Kind::Sidewalk => (palette::rgb_index(palette::H_WHITE, 2), catalog::ROAD_PAVING),
                        Kind::Park => (palette::rgb_index(palette::H_GREEN, 2), catalog::FLORA_GRASS),
                        _ => (palette::rgb_index(palette::H_WHITE, 2), catalog::ROAD_PAVING),
                    };
                    colors.push(col);
                    tiles.push(tile);
                }
            }
        }
    }

    s.push_str("#ifdef ASCITTY_CITY_DATA\n");
    emit_bytes(&mut s, "city_h", &heights);
    emit_bytes(&mut s, "city_c", &colors);
    emit_bytes(&mut s, "city_t", &tiles);
    s.push_str("#endif\n\n#endif\n");
    s
}

fn emit_bytes(s: &mut String, name: &str, data: &[u8]) {
    let _ = writeln!(s, "const unsigned char {name}[CITY_SIZE * CITY_SIZE] = {{");
    for row in data.chunks(16) {
        let _ = write!(s, "    ");
        for b in row {
            let _ = write!(s, "{b:3},");
        }
        s.push('\n');
    }
    s.push_str("};\n");
}

/// A human-readable sheet of the catalogue: index, name, the bitmap as
/// blocks, and the two terminal stand-ins.
///
/// This goes in the documentation.  A font that is generated by a function
/// still has to be *looked at* by a person, and a sheet is how.
fn sheet() -> String {
    let cat = catalog::build();
    let mut s = String::new();
    s.push_str("ASCITTY glyph catalogue - 128 shapes, generated by ascitty-core::catalog\n");
    s.push_str("idx  name          ascii unicode  bitmap\n");
    s.push_str("---------------------------------------------------------------\n");
    for i in 0..catalog::N_GLYPHS {
        let g = i as GlyphId;
        let bm: &Bitmap = &cat.bitmaps[i];
        let _ = write!(
            s,
            "{i:3}  {:<13} {}     {}       ",
            cat.names[i],
            Mode::Ascii.glyph(g),
            Mode::Unicode.glyph(g)
        );
        // Two rows of the bitmap per output line would be unreadable; print
        // it as eight quadrant characters across, which is the same trick
        // the renderer uses on the city.
        for row in 0..4 {
            let mut acc = String::new();
            for col in 0..4 {
                let m = (font::get_px(bm, col * 2, row * 2) as u8)
                    | (font::get_px(bm, col * 2 + 1, row * 2) as u8) << 1
                    | (font::get_px(bm, col * 2, row * 2 + 1) as u8) << 2
                    | (font::get_px(bm, col * 2 + 1, row * 2 + 1) as u8) << 3;
                acc.push(if m == 0 { ' ' } else { UNICODE[(catalog::G_QUAD + m - 1) as usize] });
            }
            let _ = write!(s, "|{acc}");
        }
        s.push_str("|\n");
    }
    let _ = ASCII.len();
    s
}
