//! Bakes the Rust core's tables into C headers for the 6502 build.
//!
//! This is the bridge between the two halves of the project, and the reason
//! the Plus/4 build does not have its own copy of anything.  The character
//! set, the sine table, the reciprocals and the city are all *generated by
//! the same code the terminal renderer uses*, so there is exactly one
//! definition of what a dither glyph looks like, one city generator, and one
//! answer to what colour a building is.
//!
//! The 6502 gets those answers as data.  It does not recompute them - it
//! could not afford to - and it cannot disagree with them, because it has
//! nothing to disagree with.
//!
//! Everything written here is generated, so nothing written here is
//! committed; `make bake` runs before every target build.
//!
//! ```text
//! ascitty-bake --out targets/plus4/gen
//!   charset.h   1024 bytes  the 128 glyphs, 8 bytes each, TED bit order
//!   trig.h       512 bytes  256-entry sine table in Q8.8
//!   recip.h      512 bytes  1/n in Q8.8, for the perspective divide
//!   city.h        ~3 KB     a 48x48 district: heights, colours, tiles
//!   glyphs.h        --      the catalogue's names as #defines
//! ```

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use ascitty_core::catalog::{self, GlyphId};
use ascitty_core::font::{self, Bitmap};
use ascitty_core::glyph::{Mode, ASCII, UNICODE};
use ascitty_core::palette;
use ascitty_core::trig;
use ascitty_core::world::{Arch, City, Kind, SIZE};

/// Pick the window of the city worth baking.
///
/// It used to be "the middle of the map", on the reasoning that downtown is
/// in the middle.  Downtown *is* in the middle, and so is the crossing of
/// the two arterials - which are twelve to sixteen cells wide each, so the
/// middle of the map is a hundred metres of tarmac in both directions.  The
/// baked district came out with a thirteen-row band of empty carriageway
/// through it and the attract mode spent half its time looking at nothing.
///
/// Then it was "the most built ground", scored with a summed-area table.
/// That is the opposite mistake and it looked worse.  The densest 64x64 of
/// a city is a solid block of towers, so the camera boots hard against a
/// wall: at forty columns a near facade is one flat colour across half the
/// screen, and the frame carries no sky, no distance and no second building
/// to compare the first with.  Side by side against the earlier build the
/// difference is not subtle.
///
/// What a forty-by-twenty-five screen wants is a *street*: something to look
/// down, buildings at several distances along it, and sky above.  So the
/// score is content multiplied by the length of the longest straight run of
/// road out of the district's centre - the same probe the target itself
/// does at boot to decide which way to face, so what is scored here is
/// literally what the machine will show.
///
/// This is what "size the world to the resolution" means in practice.  The
/// district is the same 64 cells either way; which 64 is chosen has to be
/// decided by what fits in forty columns, not by what is densest.
fn pick_district(c: &City) -> (usize, usize) {
    let n = SIZE;
    // Inclusive prefix sums of "is there a building here".
    let mut sum = vec![0u32; (n + 1) * (n + 1)];
    for y in 0..n {
        for x in 0..n {
            let built = u32::from(c.height(x as i32, y as i32) > 0);
            sum[(y + 1) * (n + 1) + (x + 1)] =
                built + sum[y * (n + 1) + (x + 1)] + sum[(y + 1) * (n + 1) + x]
                    - sum[y * (n + 1) + x];
        }
    }
    let area = |x0: usize, y0: usize| -> u32 {
        let (x1, y1) = (x0 + DISTRICT, y0 + DISTRICT);
        sum[y1 * (n + 1) + x1] + sum[y0 * (n + 1) + x0]
            - sum[y0 * (n + 1) + x1]
            - sum[y1 * (n + 1) + x0]
    };

    let mut best = (0usize, 0usize, 0u32, 0u32, 0u32);
    for y in 0..=(n - DISTRICT) {
        for x in 0..=(n - DISTRICT) {
            let built = area(x, y);
            // Cheap reject before the probe: a district that is mostly
            // empty cannot win however long its streets are, and the probe
            // is the expensive half.
            if built * 4 < (DISTRICT * DISTRICT) as u32 {
                continue;
            }
            let view = street_view(c, x, y);
            let score = built * view;
            if score > best.2 {
                best = (x, y, score, built, view);
            }
        }
    }
    eprintln!(
        "  district at {},{}: {} of {} cells built ({}%), {} cells of street to look down",
        best.0,
        best.1,
        best.3,
        DISTRICT * DISTRICT,
        best.3 as usize * 100 / (DISTRICT * DISTRICT),
        best.4
    );
    (best.0, best.1)
}

/// How far you can see down a street from the middle of a district.
///
/// The longest straight run of carriageway in any of the four cardinal
/// directions from the nearest road cell to the centre, capped - past about
/// the draw distance the far end is not drawn at all, so an uncapped run
/// would just elect whichever district contains the longest arterial, which
/// is the empty-tarmac failure again.
///
/// Probed all the way to the draw distance rather than to some shorter
/// figure.  A twenty-cell street sounds long and is not: the target draws
/// forty, so a tower standing at twenty-one cells closes the end of the
/// street and fills the middle of the frame - which is the wall the first
/// attempt at this produced, in a district that scored full marks for
/// having twenty cells of clear road in front of it.
///
/// Zero if there is no road near the centre at all, which rejects the
/// district outright: the target spawns at its centre.
fn street_view(c: &City, ox: usize, oy: usize) -> u32 {
    const REACH: i32 = FAR;
    const CAP: u32 = 32;
    let mid = (ox + DISTRICT / 2) as i32;
    let midy = (oy + DISTRICT / 2) as i32;

    // The same spiral the target's `spawn()` walks, bounded much tighter:
    // a centre more than a few cells from a road is not a centre.
    let mut start = None;
    'find: for r in 0..6i32 {
        for dy in -r..=r {
            for dx in -r..=r {
                if dx.abs() != r && dy.abs() != r {
                    continue;
                }
                let (x, y) = (mid + dx, midy + dy);
                if c.at(x, y).kind == Kind::Road && c.height(x, y) == 0 {
                    start = Some((x, y));
                    break 'find;
                }
            }
        }
    }
    let Some((sx, sy)) = start else { return 0 };

    let mut best = 0;
    for (dx, dy) in [(1, 0), (-1, 0), (0, 1), (0, -1)] {
        let mut run = 0;
        for k in 1..=REACH {
            let (x, y) = (sx + dx * k, sy + dy * k);
            if c.at(x, y).kind != Kind::Road || c.height(x, y) > 0 {
                break;
            }
            run += 1;
        }
        best = best.max(run as u32);
    }
    // ...multiplied by how wide the street is.
    //
    // Depth is not enough on its own.  An alley twenty cells long puts a
    // wall four metres from the camera on both sides, and at forty columns
    // that is two flat blocks of colour and nothing else.  What the earlier
    // build had - and what it was liked for - was a *wide* street: the
    // buildings are then far enough away to be several cells of facade each
    // rather than one, which is where the window texture comes from, and
    // there is sky between them.
    //
    // Capped, for the same reason the run is: the whole point of moving off
    // the arterial crossing was that a hundred metres of tarmac in both
    // directions is not a view either.
    let w = c.plan.cols.at(sx).width.max(c.plan.rows.at(sy).width) as u32;
    best.min(CAP) * w.clamp(2, 10)
}

/// Where in the district to stand, and which way to look.
///
/// Returns district-local cell coordinates and a heading as a byte of turn.
///
/// Scored on the length of clear carriageway ahead, then on how much is
/// *built* along the sides of it - a street with nothing on it is as poor a
/// first frame as a wall is, and the two failures look nothing alike so both
/// have to be scored against.  Candidates are road cells near the middle of
/// the district, because that is where the district was chosen to be
/// interesting and because the edges of a 64-cell window have no city beyond
/// them to look at.
fn pick_view(c: &City, off_x: usize, off_y: usize) -> (usize, usize, u8, u32) {
    const NEAR: i32 = 10;
    let mid = (DISTRICT / 2) as i32;
    let inside = |x: i32, y: i32| x >= 0 && y >= 0 && x < DISTRICT as i32 && y < DISTRICT as i32;
    let world = |x: i32, y: i32| ((x + off_x as i32), (y + off_y as i32));
    let road = |x: i32, y: i32| {
        let (gx, gy) = world(x, y);
        inside(x, y) && c.at(gx, gy).kind == Kind::Road && c.height(gx, gy) == 0
    };

    let mut best = (mid as usize, mid as usize, 0u8, 0u32, 0u32);
    for dy in -NEAR..=NEAR {
        for dx in -NEAR..=NEAR {
            let (x, y) = (mid + dx, mid + dy);
            if !road(x, y) {
                continue;
            }
            // Four headings, as bytes of turn: east, south, west, north -
            // the same quarters `trig` uses, which is what the target's
            // COS/SIN tables are indexed by.
            for (i, (sx, sy)) in [(1, 0), (0, 1), (-1, 0), (0, -1)].iter().enumerate() {
                let mut run = 0u32;
                let mut built = 0u32;
                for k in 1..=FAR {
                    let (px, py) = (x + sx * k, y + sy * k);
                    if !road(px, py) {
                        break;
                    }
                    run += 1;
                    // What flanks the street at this distance, one cell out
                    // on each side across the direction of travel.
                    for side in [-3, 3] {
                        let (fx, fy) = (px - sy * side, py + sx * side);
                        if inside(fx, fy) {
                            let (gx, gy) = world(fx, fy);
                            built += u32::from(c.height(gx, gy) > 0);
                        }
                    }
                }
                if (run, built) > (best.3, best.4) {
                    best = (x as usize, y as usize, (i as u8) << 6, run, built);
                }
            }
        }
    }
    (best.0, best.1, best.2, best.3)
}

/// Side of the district baked for the Plus/4, in cells.
///
/// **64, and it must be a power of two.**  The 6502 has no multiply, so a
/// grid lookup written as `y * SIZE + x` becomes a call to cc65's software
/// multiply - about a hundred cycles - and the DDA does one of those on
/// every step of every column of every frame.  At 48 wide the target build
/// ran at about one frame a second, and that multiply was most of it.  At 64
/// the index is `(y << 6) | x`, which is free.
///
/// The cost is size: 64x64 at three bytes a cell is 12 KB against 6.75 KB,
/// which the machine can afford.  The whole 128x128 city would be 48 KB and
/// could not.  The district is taken from the middle of the map, where the
/// tall buildings are.
const DISTRICT: usize = 64;

/// Bits per fractional part in the Plus/4's fixed point.
const Q: i32 = 8;

struct Opts {
    out: PathBuf,
    seed: u32,
    sheet: bool,
}

const USAGE: &str = "\
ascitty-bake - generate the 6502 build's tables from the Rust core

USAGE: ascitty-bake [options]

  --out DIR     where to write the headers (default: targets/plus4/gen)
  --seed N      city seed; must match the one the host renders
  --sheet       print the glyph catalogue as a character sheet and exit
  -h, --help    this
";

fn main() {
    let mut o = Opts {
        out: PathBuf::from("targets/plus4/gen"),
        seed: ascitty_core::DEFAULT_SEED,
        sheet: false,
    };
    let mut args = std::env::args().skip(1);
    while let Some(a) = args.next() {
        match a.as_str() {
            "-h" | "--help" => {
                print!("{USAGE}");
                return;
            }
            "--out" => o.out = PathBuf::from(args.next().expect("--out needs a directory")),
            "--seed" => o.seed = args.next().expect("--seed needs a number").parse().expect("bad seed"),
            "--sheet" => o.sheet = true,
            _ => {
                eprintln!("ascitty-bake: unknown option {a}\n\n{USAGE}");
                std::process::exit(2);
            }
        }
    }

    if o.sheet {
        print!("{}", sheet());
        return;
    }

    std::fs::create_dir_all(&o.out).expect("cannot create the output directory");
    write(&o.out, "charset.h", &charset());
    write(&o.out, "tables.h", &tables());
    write(&o.out, "trig.h", &trig_table());
    write(&o.out, "recip.h", &recip_table());
    write(&o.out, "glyphs.h", &glyph_defines());
    write(&o.out, "city.h", &city(o.seed));
    eprintln!("baked into {}", o.out.display());
}

fn write(dir: &Path, name: &str, body: &str) {
    let path = dir.join(name);
    std::fs::write(&path, body).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    eprintln!("  {} {} bytes", path.display(), body.len());
}

/// The banner every generated header carries.
fn banner(what: &str) -> String {
    format!(
        "/* {what}\n\
         **\n\
         ** GENERATED by ascitty-bake from the ascitty-core crate.\n\
         ** Do not edit: `make bake` overwrites this file, and the generator\n\
         ** is the definition of what these numbers are.\n\
         */\n\n"
    )
}

/// The 128 glyphs, as the TED wants them: one byte per row, bit 7 leftmost.
fn charset() -> String {
    let cat = catalog::build();
    let mut s = banner("charset.h - the procedural block font, 128 glyphs of 8 bytes");
    s.push_str("#ifndef ASCITTY_CHARSET_H\n#define ASCITTY_CHARSET_H\n\n");
    let _ = writeln!(s, "#define CHARSET_GLYPHS {}", catalog::N_GLYPHS);
    let _ = writeln!(s, "#define CHARSET_BYTES  {}\n", catalog::N_GLYPHS * 8);
    s.push_str("extern const unsigned char charset[CHARSET_BYTES];\n\n");
    s.push_str("#ifdef ASCITTY_CHARSET_DATA\nconst unsigned char charset[CHARSET_BYTES] = {\n");
    for (i, bm) in cat.bitmaps.iter().enumerate() {
        let _ = write!(s, "    ");
        for b in bm {
            let _ = write!(s, "0x{b:02x},");
        }
        let _ = writeln!(s, " /* {i:3} {} */", cat.names[i]);
    }
    s.push_str("};\n#endif\n\n#endif\n");
    s
}

/// Sine in Q8.8, 256 entries - a quarter of the host's resolution, which at
/// 40 columns is a third of a character.
fn trig_table() -> String {
    let mut s = banner("trig.h - sine over one turn, Q8.8, 256 entries");
    s.push_str("#ifndef ASCITTY_TRIG_H\n#define ASCITTY_TRIG_H\n\n");
    s.push_str("#define TRIG_LEN  256\n#define TRIG_ONE  256\n");
    s.push_str("#define SIN(a)  (sintab[(unsigned char)(a)])\n");
    s.push_str("#define COS(a)  (sintab[(unsigned char)((a) + 64)])\n\n");
    s.push_str("extern const int sintab[TRIG_LEN];\n\n");
    s.push_str("#ifdef ASCITTY_TRIG_DATA\nconst int sintab[TRIG_LEN] = {\n");
    for row in 0..32 {
        let _ = write!(s, "    ");
        for col in 0..8 {
            let i = row * 8 + col;
            let a = (i as u32 * 65536 / 256) as u16;
            // Q16.16 down to Q8.8, rounding rather than truncating: the
            // truncated table is biased towards zero and a biased sine puts
            // a slow drift into every heading.
            let v = (ascitty_core::trig::sin(a) + 128) >> 8;
            let _ = write!(s, "{v:5},");
        }
        s.push('\n');
    }
    s.push_str("};\n#endif\n\n#endif\n");
    let _ = trig::TRIG_LEN;
    s
}

/// `1/n` in Q8.8 for `n` in `1..=255`.
///
/// The perspective divide is the only division the inner loop needs, and a
/// 6502 has no divide instruction at all - a 16-bit software divide is
/// upwards of 400 cycles.  A 512-byte table replaces every one of them with
/// a multiply, which the machine also lacks but which is four times cheaper
/// to synthesise.
fn recip_table() -> String {
    let mut s = banner("recip.h - 65536/n in Q8.8, for the DDA's step distances");
    s.push_str("#ifndef ASCITTY_RECIP_H\n#define ASCITTY_RECIP_H\n\n");
    // 512 entries, not 256.  The table is indexed by the magnitude of a ray
    // direction component in Q8.8, which reaches 1.0 for the direction plus
    // 0.67 for the plane - about 427 - so a 256-entry table would run off
    // the end for every ray in the outer third of the screen.
    s.push_str("#define RECIP_LEN 512\n\n");
    s.push_str("extern const unsigned int reciptab[RECIP_LEN];\n\n");
    s.push_str("#ifdef ASCITTY_RECIP_DATA\nconst unsigned int reciptab[RECIP_LEN] = {\n");
    for row in 0..64 {
        let _ = write!(s, "    ");
        for col in 0..8 {
            let n = row * 8 + col;
            // Entry 0 is "infinitely near", clamped to the largest value the
            // callers can multiply by without overflowing 16 bits.
            let v: u32 = if n == 0 { 0xffff } else { ((1u32 << (2 * Q)) / n as u32).min(0xffff) };
            // cc65 promotes an unsuffixed constant above INT_MAX to long,
            // and then warns about every entry of the table.  The suffix is
            // not decoration.
            let _ = write!(s, "{v:5}U,");
        }
        s.push('\n');
    }
    s.push_str("};\n#endif\n\n#endif\n");
    s
}

/// Screen geometry of the Plus/4, which the baked tables are sized for.
const SCR_W: i32 = 40;
const SCR_H: i32 = 25;
/// Rows per world unit at unit distance, on that screen.
const PROJ: i32 = 15;
/// Longest ray, in whole cells.
const FAR: i32 = 40;
/// Horizontal field of view, in degrees.  The one place it is decided.
const FOV_DEGREES: f64 = 67.0;

/// Everything the target used to work out at boot.
///
/// Five tables and a multiplication table.  The renderer on the machine now
/// starts by reading, not by dividing: the boot code had 41 divisions for
/// the projection, 40 for the column offsets and 256 modulos for the star
/// field, and every one of them was recomputing a number this program
/// already knows.
///
/// The correctness argument matters more than the cycles. These are the
/// *same* formulas the host renderer uses, evaluated once, here - so the two
/// targets cannot drift apart by someone retuning a constant on one side.
fn tables() -> String {
    let mut s = banner("tables.h - everything the target would otherwise work out at boot");
    s.push_str("#ifndef ASCITTY_TABLES_H\n#define ASCITTY_TABLES_H\n\n");

    let _ = writeln!(s, "#define SCR_W {SCR_W}");
    let _ = writeln!(s, "#define SCR_H {SCR_H}");
    let _ = writeln!(s, "#define PROJ  {PROJ}");
    let _ = writeln!(s, "#define FAR   {FAR}");
    let _ = writeln!(s, "#define HORIZON (SCR_H / 2)\n");

    // The camera plane half-width, in Q8.8, from the field of view in
    // degrees.  See `camera::fov_for_degrees`.
    let fov = (FOV_DEGREES / 2.0).to_radians().tan();
    let _ = writeln!(s, "/* Field of view: {FOV_DEGREES} degrees, as a camera-plane half-width. */");
    let _ = writeln!(s, "#define FOV {}\n", (fov * 256.0).round() as i32);

    // The light bearing, as one byte of turn.  The same constant the host
    // lights from and the same one the baked shadows were swept for - if
    // the target lit from a different direction than its own shadows were
    // cast from, the two would disagree and nothing would say so.
    let _ = writeln!(s, "/* Light bearing, from ascitty_core::shadow::DEFAULT_AZ. */");
    let _ = writeln!(s, "#define MOON_AZ {}\n", ascitty_core::shadow::DEFAULT_AZ >> 8);

    s.push_str("/* Rows per world unit at distance d, Q4.4. */\n");
    let proj: Vec<i32> = (0..=FAR + 1)
        .map(|d| if d == 0 { PROJ * 16 } else { PROJ * 16 / d })
        .collect();
    emit_table(&mut s, "projtab", "unsigned int", &proj);

    s.push_str("/* Luminance steps lost to haze at distance d. */\n");
    let fade: Vec<i32> = (0..=FAR + 1).map(|d| d * 7 / FAR).collect();
    emit_table(&mut s, "fadetab", "unsigned char", &fade);

    s.push_str("/* Camera-plane offset per screen column, Q8.8, -255..255. */\n");
    let camx: Vec<i32> = (0..SCR_W)
        .map(|x| (x * 512 / SCR_W - 256).clamp(-255, 255))
        .collect();
    emit_table(&mut s, "camxtab", "int", &camx);

    s.push_str("/* Colour of each road row below the horizon. */\n");
    let ground: Vec<i32> = (0..SCR_H)
        .map(|d| {
            // The target computed this in an `unsigned char`, so rows past
            // the horizon wrapped negative and fell into the far branch.
            // Reproduced rather than corrected: the rows it affects are the
            // ones below the bottom of the screen, and "the same numbers as
            // before" is worth more here than "the numbers I would pick now".
            let away = (SCR_H - (SCR_H / 2) - d).rem_euclid(256);
            let l = if away >= 8 { 1 } else { (3 - (away >> 2)).max(1) };
            (l << 4) | palette::H_WHITE as i32
        })
        .collect();
    emit_table(&mut s, "groundtab", "unsigned char", &ground);

    s.push_str("/* Which row a column's star sits on, by column plus heading. */\n");
    let star: Vec<i32> = (0..256)
        .map(|i: i32| 1 + (i * 7 + (i >> 3)) % (SCR_H / 2 - 1))
        .collect();
    emit_table(&mut s, "startab", "unsigned char", &star);

    s.push_str(
        "/* Quarter squares: qsq[n] = n*n/4.\n\
         **\n\
         ** An 8x8 multiply without a multiply, which a 6502 does not have:\n\
         **\n\
         **     a*b = (a+b)^2/4 - (a-b)^2/4\n\
         **\n\
         ** and the floors cancel exactly, because a+b and a-b always share a\n\
         ** parity.  Two table reads and a subtraction against cc65's\n\
         ** software multiply.  511 entries because a+b reaches 510; the\n\
         ** largest value is 510^2/4 = 65025, which is the reason this is the\n\
         ** widest table that still fits an unsigned int. */\n",
    );
    let qsq: Vec<i32> = (0..511).map(|n: i32| n * n / 4).collect();
    emit_table(&mut s, "qsq", "unsigned int", &qsq);

    s.push_str("#endif\n");
    s
}

/// Emit one table as an extern plus a guarded definition.
fn emit_table(s: &mut String, name: &str, ctype: &str, data: &[i32]) {
    let _ = writeln!(s, "#define {}_LEN {}", name.to_uppercase(), data.len());
    let _ = writeln!(s, "extern const {ctype} {name}[{}_LEN];", name.to_uppercase());
    let _ = writeln!(s, "#ifdef ASCITTY_TABLES_DATA");
    let _ = writeln!(s, "const {ctype} {name}[{}_LEN] = {{", name.to_uppercase());
    for row in data.chunks(8) {
        let _ = write!(s, "    ");
        for v in row {
            // cc65 promotes an unsigned constant above INT_MAX to long.
            let suffix = if *v > 32767 { "U" } else { "" };
            let _ = write!(s, "{v}{suffix},");
        }
        s.push('\n');
    }
    let _ = writeln!(s, "}};\n#endif\n");
}

/// The catalogue's names, so the C reads like the Rust.
fn glyph_defines() -> String {
    let mut s = banner("glyphs.h - catalogue indices, which are also screen codes");
    s.push_str("#ifndef ASCITTY_GLYPHS_H\n#define ASCITTY_GLYPHS_H\n\n");
    let defs: [(&str, GlyphId); 22] = [
        ("G_BLANK", catalog::G_BLANK),
        ("G_DITHER", catalog::G_DITHER),
        ("G_SOLID", catalog::G_SOLID),
        ("G_QUAD", catalog::G_QUAD),
        ("G_FILL", catalog::G_FILL),
        ("G_SLOPE", catalog::G_SLOPE),
        ("G_FACADE", catalog::G_FACADE),
        ("G_MULLION", catalog::G_MULLION),
        ("G_CORNICE", catalog::G_CORNICE),
        ("G_FIRE", catalog::G_FIRE),
        ("G_ROOF", catalog::G_ROOF),
        ("G_ROAD", catalog::G_ROAD),
        ("ROAD_ASPHALT", catalog::ROAD_ASPHALT),
        ("ROAD_DASH", catalog::ROAD_DASH),
        ("ROAD_CENTRE", catalog::ROAD_CENTRE),
        ("ROAD_KERB", catalog::ROAD_KERB),
        ("ROAD_PAVING", catalog::ROAD_PAVING),
        ("G_FLORA", catalog::G_FLORA),
        ("G_STREET", catalog::G_STREET),
        ("G_RAIN", catalog::G_RAIN),
        ("G_STAR", catalog::G_STAR),
        ("G_HAZE", catalog::G_HAZE),
    ];
    for (name, v) in defs {
        let _ = writeln!(s, "#define {name:<14} {v}");
    }
    s.push_str("\n/* A TED colour byte: luminance in the high nibble, hue in the low. */\n");
    s.push_str("#define CBYTE(lum, hue) ((unsigned char)(((lum) << 4) | (hue)))\n\n");
    s.push_str("/* Hues, in TED order. */\n");
    for (name, v) in [
        ("HUE_BLACK", palette::H_BLACK),
        ("HUE_WHITE", palette::H_WHITE),
        ("HUE_RED", palette::H_RED),
        ("HUE_CYAN", palette::H_CYAN),
        ("HUE_GREEN", palette::H_GREEN),
        ("HUE_BLUE", palette::H_BLUE),
        ("HUE_YELLOW", palette::H_YELLOW),
        ("HUE_ORANGE", palette::H_ORANGE),
    ] {
        let _ = writeln!(s, "#define {name:<12} {v}");
    }
    s.push_str("\n#endif\n");
    s
}

/// A district of the city, as three parallel byte arrays.
///
/// Structure-of-arrays rather than array-of-structs, because the 6502
/// indexes a byte array with one instruction and a struct array with a
/// multiply it does not have.
fn city(seed: u32) -> String {
    let c = City::generate(seed);
    let (off_x, off_y) = pick_district(&c);
    let mut s = banner("city.h - a district of the generated city, as a height field");
    s.push_str("#ifndef ASCITTY_CITY_H\n#define ASCITTY_CITY_H\n\n");
    let _ = writeln!(s, "#define CITY_SIZE {DISTRICT}");
    let _ = writeln!(s, "#define CITY_SHIFT {}", DISTRICT.trailing_zeros());
    let _ = writeln!(s, "#define CITY_MASK  {}", DISTRICT - 1);
    s.push_str("/* CITY_SIZE is a power of two so that a grid index is a shift.\n");
    s.push_str("** See the note in ascitty-bake; it is worth a factor of three. */\n");
    let _ = writeln!(s, "#define CITY_SEED {seed}U");
    let _ = writeln!(s, "#define CITY_ORIGIN_X {off_x}");
    let _ = writeln!(s, "#define CITY_ORIGIN_Y {off_y}");

    // Where the camera stands and which way it looks, chosen here rather
    // than searched for at boot.
    //
    // The machine used to spiral out from the middle of the district for a
    // road cell and then probe four directions for the longest street.  Both
    // searches are pure functions of data this program already holds, so
    // both are now done here: the target reads three numbers.  That is the
    // bake bridge working as intended, and it also fixes what the boot-time
    // version got wrong - it could only see 24 cells, so it could not tell a
    // street that runs off into the haze from one a tower closes at 25, and
    // it opened on a facade filling the middle of the screen.
    let (sx, sy, sa, run) = pick_view(&c, off_x, off_y);
    eprintln!("  camera at {sx},{sy} facing {sa}, {run} cells of clear street");
    let _ = writeln!(s, "/* Where the camera starts, in district cells, and its heading. */");
    let _ = writeln!(s, "#define START_X {sx}");
    let _ = writeln!(s, "#define START_Y {sy}");
    let _ = writeln!(s, "#define START_A {sa}\n");
    s.push_str("/* Height in world units, 0 for anything you can drive on. */\n");
    s.push_str("extern const unsigned char city_h[CITY_SIZE * CITY_SIZE];\n");
    s.push_str("/* TED colour byte of the facade, at full luminance. */\n");
    s.push_str("extern const unsigned char city_c[CITY_SIZE * CITY_SIZE];\n");
    s.push_str("/* Catalogue index of the facade tile this lot is drawn in. */\n");
    s.push_str("extern const unsigned char city_t[CITY_SIZE * CITY_SIZE];\n");
    s.push_str("/* Height of the shadow line at this cell, in whole cells.\n");
    s.push_str("**\n");
    s.push_str("** Cast shadows, for nothing at all.  The shadow line is a pure\n");
    s.push_str("** function of the height field and the light direction, and both are\n");
    s.push_str("** known here - so the machine does not sweep anything at boot, it\n");
    s.push_str("** reads an array.  A textbook renderer would trace a second ray per\n");
    s.push_str("** light per hit; this one indexes. */\n");
    s.push_str("extern const unsigned char city_s[CITY_SIZE * CITY_SIZE];\n\n");

    let mut heights = Vec::with_capacity(DISTRICT * DISTRICT);
    let mut colors = Vec::with_capacity(DISTRICT * DISTRICT);
    let mut tiles = Vec::with_capacity(DISTRICT * DISTRICT);
    let mut shade = Vec::with_capacity(DISTRICT * DISTRICT);
    for y in 0..DISTRICT {
        for x in 0..DISTRICT {
            let (gx, gy) = ((x + off_x) as i32, (y + off_y) as i32);
            let cell = c.at(gx, gy);
            heights.push(c.height(gx, gy));
            // Whole cells: the target's projection works in whole cells of
            // height anyway, and a byte per cell of district is 4 KB.
            shade.push(
                ascitty_core::fixed::floor(c.shadow.line_at(gx, gy)).clamp(0, 255) as u8,
            );
            match c.lot_at(gx, gy) {
                Some(lot) => {
                    // The building's own brightness, not a constant: the
                    // Plus/4 gets the same variety the host does.
                    colors.push(palette::rgb_index(lot.hue, lot.luma));
                    // The tile the whole building is drawn in - the same
                    // per-lot choice the host makes, resolved once here so
                    // the 6502 never has to hash anything.
                    let style = (lot.seed >> 17) as u8 & 3;
                    let cfg = match lot.arch {
                        Arch::CurtainWall | Arch::Setback => 0,
                        Arch::Slab | Arch::Deco => 1,
                        Arch::Prewar => 2,
                        Arch::LowRise => 3,
                    };
                    tiles.push(catalog::facade_tile(cfg, style));
                }
                None => {
                    let (col, tile) = match cell.kind {
                        Kind::Road => (palette::rgb_index(palette::H_WHITE, 1), catalog::ROAD_ASPHALT),
                        Kind::Sidewalk => (palette::rgb_index(palette::H_WHITE, 2), catalog::ROAD_PAVING),
                        Kind::Park => (palette::rgb_index(palette::H_GREEN, 2), catalog::FLORA_GRASS),
                        _ => (palette::rgb_index(palette::H_WHITE, 2), catalog::ROAD_PAVING),
                    };
                    colors.push(col);
                    tiles.push(tile);
                }
            }
        }
    }

    s.push_str("#ifdef ASCITTY_CITY_DATA\n");
    emit_bytes(&mut s, "city_h", &heights);
    emit_bytes(&mut s, "city_c", &colors);
    emit_bytes(&mut s, "city_t", &tiles);
    emit_bytes(&mut s, "city_s", &shade);
    s.push_str("#endif\n\n#endif\n");
    s
}

fn emit_bytes(s: &mut String, name: &str, data: &[u8]) {
    let _ = writeln!(s, "const unsigned char {name}[CITY_SIZE * CITY_SIZE] = {{");
    for row in data.chunks(16) {
        let _ = write!(s, "    ");
        for b in row {
            let _ = write!(s, "{b:3},");
        }
        s.push('\n');
    }
    s.push_str("};\n");
}

/// A human-readable sheet of the catalogue: index, name, the bitmap as
/// blocks, and the two terminal stand-ins.
///
/// This goes in the documentation.  A font that is generated by a function
/// still has to be *looked at* by a person, and a sheet is how.
fn sheet() -> String {
    let cat = catalog::build();
    let mut s = String::new();
    s.push_str("ASCITTY glyph catalogue - 128 shapes, generated by ascitty-core::catalog\n");
    s.push_str("idx  name          ascii unicode  bitmap\n");
    s.push_str("---------------------------------------------------------------\n");
    for i in 0..catalog::N_GLYPHS {
        let g = i as GlyphId;
        let bm: &Bitmap = &cat.bitmaps[i];
        let _ = write!(
            s,
            "{i:3}  {:<13} {}     {}       ",
            cat.names[i],
            Mode::Ascii.glyph(g),
            Mode::Unicode.glyph(g)
        );
        // Two rows of the bitmap per output line would be unreadable; print
        // it as eight quadrant characters across, which is the same trick
        // the renderer uses on the city.
        for row in 0..4 {
            let mut acc = String::new();
            for col in 0..4 {
                let m = (font::get_px(bm, col * 2, row * 2) as u8)
                    | (font::get_px(bm, col * 2 + 1, row * 2) as u8) << 1
                    | (font::get_px(bm, col * 2, row * 2 + 1) as u8) << 2
                    | (font::get_px(bm, col * 2 + 1, row * 2 + 1) as u8) << 3;
                acc.push(if m == 0 { ' ' } else { UNICODE[(catalog::G_QUAD + m - 1) as usize] });
            }
            let _ = write!(s, "|{acc}");
        }
        s.push_str("|\n");
    }
    let _ = ASCII.len();
    s
}
